{-# LANGUAGE TemplateHaskell #-}
import ErrorLocation


main = do
  -- $(undef)
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
  $(err "Oh no!")
